name: 'Create GCP Service Account (2-Step)'

on:
  workflow_dispatch: # Allow manual triggering from the GitHub Actions UI
    inputs:
      gcp_project_id:
        description: 'The GCP Project ID where the service account will be created'
        required: true
        type: string
      service_account_name:
        description: 'The unique ID for the new service account (e.g., my-app-sa). Do not include the project details.'
        required: true
        type: string
      display_name:
        description: 'A user-friendly description for the service account'
        required: true
        type: string

jobs:
  # =================================================================
  # JOB 1: VALIDATE AND DRY RUN
  # This job confirms which service account in which project will be created.
  # =================================================================
  dry-run:
    name: 'Step 1: Validate & Dry Run Creation'
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      # Authenticate to GCP early to validate credentials
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      # Set up gcloud and configure the project context
      - name: 'Set up gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: '${{ inputs.gcp_project_id }}'

      - name: 'Display Creation Plan'
        run: |
          echo "✅ DRY RUN: The next job will create a service account with the following details:"
          echo "--------------------------------------------------"
          echo "Project ID:          ${{ inputs.gcp_project_id }}"
          echo "Service Account ID:  ${{ inputs.service_account_name }}"
          echo "Display Name:        ${{ inputs.display_name }}"
          echo " "
          echo "Full Email will be:  ${{ inputs.service_account_name }}@${{ inputs.gcp_project_id }}.iam.gserviceaccount.com"
          echo "--------------------------------------------------"
          echo " "
          echo "If this is incorrect, cancel the workflow run now."


  # =================================================================
  # JOB 2: APPLY CREATION
  # This job runs automatically after the dry-run job succeeds.
  # =================================================================
  execute-creation:
    name: 'Step 2: Apply Creation'
    runs-on: ubuntu-latest
    needs: dry-run # Ensures the dry-run job completes successfully first
    if: github.event_name == 'workflow_dispatch' # Safety check

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: 'Set up gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: '${{ inputs.gcp_project_id }}'

      - name: 'Execute Creation of Service Account'
        run: |
          echo "🚀 Applying creation for service account: ${{ inputs.service_account_name }} in project: ${{ inputs.gcp_project_id }}"
          gcloud iam service-accounts create ${{ inputs.service_account_name }} \
            --project=${{ inputs.gcp_project_id }} \
            --display-name="${{ inputs.display_name }}"
          echo "✅ Successfully created service account."
