name: 'Delete GCP Service Account (2-Step)'

on:
  workflow_dispatch: # Allow manual triggering from the GitHub Actions UI
    inputs:
      service_account_email:
        description: 'The full email of the GCP service account to delete'
        required: true
        type: string

jobs:
  # =================================================================
  # JOB 1: VALIDATE AND DRY RUN
  # This job confirms which service account will be deleted.
  # =================================================================
  dry-run:
    name: 'Step 1: Validate & Dry Run Deletion'
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      # Authentication is included here to verify credentials early
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}' # SA that will perform the deletion

      # Setting up gcloud validates that the CLI tool is ready for the next job
      - name: 'Set up gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Display Deletion Plan'
        run: |
          echo "✅ DRY RUN: The next job will delete the following service account:"
          echo "➡️   ${{ inputs.service_account_email }}"
          echo " "
          echo "If this is incorrect, cancel the workflow run now."


  # =================================================================
  # JOB 2: APPLY DELETION
  # This job runs automatically after the dry-run job succeeds.
  # =================================================================
  execute-deletion:
    name: 'Step 2: Apply Deletion'
    runs-on: ubuntu-latest
    needs: dry-run # Ensures the dry-run job completes successfully first
    if: github.event_name == 'workflow_dispatch' # Safety check to only run when manually triggered

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: 'Set up gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Execute Deletion of Service Account'
        run: |
          echo "🚀 Applying deletion for service account: ${{ inputs.service_account_email }}"
          gcloud iam service-accounts delete ${{ inputs.service_account_email }} --quiet
          echo "✅ Successfully deleted service account."
