# Save this as a new file in .github/workflows/infoblox-delete-cidr.yaml
name: 'Infoblox: Delete CIDR Reservation'

on:
  workflow_dispatch:
    inputs:
      network_view:
        description: 'Select the Network View where the subnet exists'
        required: true
        type: string
        default: 'gcp-netnet-d-vie'
      subnet_cidr:
        description: 'Enter the exact CIDR of the subnet to delete (e.g., 100.45.3.4/28)'
        required: true
        type: string

jobs:
  dry-run:
    name: 'Plan: Find subnet to delete'
    runs-on: ubuntu-latest
    environment: infoblox-prod # An environment with read access

    # This section makes the subnet's internal reference ID (_ref) available
    # to the 'apply' job.
    outputs:
      subnet_ref: ${{ steps.find_subnet_step.outputs.subnet_ref }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Get Infoblox Credentials from Secret Manager
        run: |
          set -e
          SECRET_USERNAME_NAME="${{ secrets.INFOBLOX_SECRET_USERNAME }}"
          SECRET_PASSWORD_NAME="${{ secrets.INFOBLOX_SECRET_PASSWORD }}"
          
          # IMPORTANT: Replace YOUR_GCP_PROJECT_ID with your actual project ID or a secret ref
          GCLOUD_PROJECT="YOUR_GCP_PROJECT_ID" 

          INFOBLOX_USERNAME=$(gcloud secrets versions access latest --secret="${SECRET_USERNAME_NAME}" --project="${GCLOUD_PROJECT}")
          INFOBLOX_PASSWORD=$(gcloud secrets versions access latest --secret="${SECRET_PASSWORD_NAME}" --project="${GCLOUD_PROJECT}")
          
          echo "INFOBLOX_USERNAME=$INFOBLOX_USERNAME" >> $GITHUB_ENV
          echo "INFOBLOX_PASSWORD=$INFOBLOX_PASSWORD" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: pip install requests

      - name: Find Subnet to be Deleted (Dry Run)
        id: find_subnet_step
        run: |
          # IMPORTANT: Replace 'infoblox_delete_cidr.py' with the name of your new Python script
          python infoblox_delete_cidr.py dry-run \
            --infoblox-url ${{ secrets.INFOBLOX_URL }} \
            --network-view "${{ github.event.inputs.network_view }}" \
            --subnet-cidr "${{ github.event.inputs.subnet_cidr }}"
        env:
          INFOBLOX_USERNAME: ${{ env.INFOBLOX_USERNAME }}
          INFOBLOX_PASSWORD: ${{ env.INFOBLOX_PASSWORD }}

  apply:
    name: 'Apply: Delete the subnet'
    runs-on: ubuntu-latest
    needs: dry-run
    
    # Use a GitHub Environment with a "Required reviewers" rule for manual approval.
    # This is the safest way to prevent accidental deletions.
    environment: infoblox-prod 
    
    # This condition ensures the job only runs if the dry-run found a valid subnet.
    if: success() && needs.dry-run.outputs.subnet_ref != ''

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Get Infoblox Credentials from Secret Manager
        run: |
          set -e
          SECRET_USERNAME_NAME="${{ secrets.INFOBLOX_SECRET_USERNAME }}"
          SECRET_PASSWORD_NAME="${{ secrets.INFOBLOX_SECRET_PASSWORD }}"
          
          GCLOUD_PROJECT="YOUR_GCP_PROJECT_ID" # Replace with your project ID

          INFOBLOX_USERNAME=$(gcloud secrets versions access latest --secret="${SECRET_USERNAME_NAME}" --project="${GCLOUD_PROJECT}")
          INFOBLOX_PASSWORD=$(gcloud secrets versions access latest --secret="${SECRET_PASSWORD_NAME}" --project="${GCLOUD_PROJECT}")
          
          echo "INFOBLOX_USERNAME=$INFOBLOX_USERNAME" >> $GITHUB_ENV
          echo "INFOBLOX_PASSWORD=$INFOBLOX_PASSWORD" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: pip install requests

      - name: Delete the Subnet (Apply)
        run: |
          echo "Applying deletion for subnet with reference: ${{ needs.dry-run.outputs.subnet_ref }}"
          # IMPORTANT: Replace 'infoblox_delete_cidr.py' with the name of your new Python script
          python infoblox_delete_cidr.py apply \
            --infoblox-url ${{ secrets.INFOBLOX_URL }} \
            --subnet-ref "${{ needs.dry-run.outputs.subnet_ref }}"
        env:
          INFOBLOX_USERNAME: ${{ env.INFOBLOX_USERNAME }}
          INFOBLOX_PASSWORD: ${{ env.INFOBLOX_PASSWORD }}
